-- Create database (optional)
-- CREATE DATABASE IF NOT EXISTS it_monitoring_region8 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- USE it_monitoring_region8;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(64) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  nama VARCHAR(128) NOT NULL,
  role ENUM('Admin','User') NOT NULL DEFAULT 'User',
  pn VARCHAR(32) DEFAULT NULL,
  jabatan VARCHAR(128) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS perangkat (
  id VARCHAR(64) NOT NULL,
  main_branch VARCHAR(64) DEFAULT NULL,
  branch_office VARCHAR(128) DEFAULT NULL,
  kode_branch VARCHAR(32) DEFAULT NULL,
  nama_uker VARCHAR(256) DEFAULT NULL,
  nama_perangkat VARCHAR(128) DEFAULT NULL,
  serial_number VARCHAR(128) DEFAULT NULL,
  merk VARCHAR(128) DEFAULT NULL,
  model VARCHAR(128) DEFAULT NULL,
  processor VARCHAR(128) DEFAULT NULL,
  ram VARCHAR(64) DEFAULT NULL,
  os VARCHAR(128) DEFAULT NULL,
  tahun_penerimaan VARCHAR(8) DEFAULT NULL,
  kondisi VARCHAR(256) DEFAULT NULL,
  status VARCHAR(64) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_branch_office (branch_office),
  INDEX idx_kode_branch (kode_branch),
  INDEX idx_tahun (tahun_penerimaan)
) ENGINE=InnoDB;
